dist: focal
arch: ppc64le
language: go

services:
  - docker
  
before_install:
  - go get github.com/onsi/ginkgo/ginkgo

go:
  - "1.13.x"

env:
  - IMAGE_REGISTRY=quay.io/rh-marketplace

jobs:
  include:
    - stage: test
      script: 
              #- docker --version
              - export DOCKER_CLI_EXPERIMENTAL=enabled
              - export DOCKER_BUILDKIT=1
              #- docker build -t "public-image-registry.apps-crc.testing/symposium/redhat-marketplace-operator:1.0.4" -f build/Dockerfile .
              - docker build --build-arg ARCH=ppc64le -t "quay.io/rh-marketplace/golang-base:1.15" -f build/base.Dockerfile .
              - docker build -t "public-image-registry.apps-crc.testing/symposium/redhat-marketplace-metric-state:1.0.4" -f build/metricState.Dockerfile .
              #- docker build -t "public-image-registry.apps-crc.testing/symposium/redhat-marketplace-reporter:1.0.4" -f build/reporter.Dockerfile .
              #- docker build -t "public-image-registry.apps-crc.testing/symposium/redhat-marketplace-authcheck:1.0.4" -f build/authcheck.Dockerfile .
              
              #- make test-ci-unit
